### ISSUE TITLE
Tests Failure

### ISSUE THREAD

**Issue by yoannkubera** [sohaibafifi/vrp-gpu#2]
# Context
Errors are obtained when running the tests in the following environment :

* Ubuntu 20.04 LTS
* Apache Maven 3.6.3
* openjdk version "1.8.0_292"

From the branch : `dev` (commit 490087cdf0a371d72687154bb355b27add33e33c)

Command used : `mvn test`

# Error

Error displayed in `target/surefire-reports/fr.univ_artois.lgi2a.vrpgpu.DecoderTest.txt` :

> -------------------------------------------------------------------------------
> Test set: fr.univ_artois.lgi2a.vrpgpu.DecoderTest
> -------------------------------------------------------------------------------
> Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.145 sec <<< FAILURE!
> run(fr.univ_artois.lgi2a.vrpgpu.DecoderTest)  Time elapsed: 0.088 sec  <<< ERROR!
> java.lang.NullPointerException
> 	at com.aparapi.internal.kernel.KernelProfile.onEvent(KernelProfile.java:92)
> 	at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1702)
> 	at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1343)
> 	at com.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1333)
> 	at com.aparapi.Kernel.execute(Kernel.java:2856)
> 	at com.aparapi.Kernel.execute(Kernel.java:2813)
> 	at com.aparapi.Kernel.execute(Kernel.java:2753)
> 	at fr.univ_artois.lgi2a.vrpgpu.DecoderTest.run(DecoderTest.java:90)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
> 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
> 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by yoannkubera** [comment]
According to https://github.com/Syncleus/aparapi/issues/74, the issue seems to be related to OpenCL.

On the system used in the test, the `clinfo` command returned the following information, seemingly telling that no OpenCL compatible features were found :

>Number of platforms                               0

**Comment by yoannkubera** [comment]
The issue is located in an unmaintained branch.
Therefore, closing the issue.
